---
- name: Deploy WAR to Tomcat
  hosts: all
  become: yes

  tasks:
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Tomcat9
      apt:
        name: tomcat9
        state: present
      when: ansible_os_family == "Debian"

    - name: Copy WAR file to Tomcat webapps
   copy:
     src: target/POC-2.war
     dest: /var/lib/tomcat9/webapps/POC-2.war
     owner: tomcat
     group: tomcat
     mode: '0644'

  
    - name: Restart Tomcat
      service:
        name: tomcat9
        state: restarted
